### ISSUE TITLE
Sent/Received ticks currently missing on UT

### ISSUE THREAD

**Issue by casimir7** [nanu-c/axolotl#91] opened 2019-10-24 19:30 UTC
As of version 0.46 the ticks indicating that a message was sent or received disappeared (at least on the UT version, Axolotl 0.70)

- As a message was sent successful, the first tick should appear. 
- If the message was received on the other side, a second tick should turn up.

**Comment by yo-k** [comment] 2019-10-24 19:39
I can confirm this.

**Comment by nanu-c** [comment] 2019-10-24 19:50
The code tells  in 0.46, first tick, when message was created, second tick, when it was successfully send to signal ;) so it never worked as intended...

**Comment by yo-k** [comment] 2019-10-24 20:14
@nanu-c yes, you mentioned it elsewhere in #73 
> The old app is lying with this ticks, it does indicate if the message was sent, but not as on android showing if the message was read, i am also not so much into spying on people, so i add it to the second list :)

The spy tick is not important for me, too. One tick helps to indicate whether the message got the way to the server.

**Comment by casimir7** [comment] 2019-10-25 08:08
@nanu-c : Ok, then the old behavior in 0.46 was indeed quite useless.
Syping is not the intention here, as the indicator should not show if the message was read but only to assure that the message was delivered to the other device. This is useful because it could avoid problems like I had when I was unregistered after an update without knowing it and people would send messages and ask me days later "Did you not get my messages?" So, this is about a confirmation that the technical layer of the transmission worked, not if the person read the message. However, I don't know if others would find that useful and if it's possible to implement such functionality within Signal's protocol.

**Comment by Flaburgan** [comment] 2020-09-26 21:25
I'll try to work on that issue in the coming weeks.

**Comment by Flaburgan** [comment] 2020-11-08 13:02
Good news everyone, the ticks are now back and will indicate when the message status is sending, sent, delivered and read. This will be part of the next minor version, 0.9.

**Closed by Flaburgan** 2020-11-08 13:02 UTC
Labels: enhancement
