### ISSUE TITLE
[BUG] Unable to send photo

### ISSUE THREAD

**Issue by ChrisAWC** [nanu-c/axolotl#330] opened 2021-01-26 11:46 UTC
### Description
Unable to send photo

### Steps to Reproduce

1. Choose recipient
2. Tap “+” > Photo > Gallery> tap photo > and send

**Expected behavior:** 
Photo to be sent

**Actual behavior:** 
Image darkened, spinning circle in centre, red surround to green photo border. Present now for >1 week. Phone heats up. 
Uninstalling Axolotl is the only way I have found to cool the phone again. Deleted photo in Gallery without effect.
Reinstalling Axolotl and the unsent image with spinning circle is still there.

On repeated attempt to send photo, the photo was sent, but the original attempt is still frozen as above.

#### Versions
Axolotl Beta 0.9.5
Ubuntu16.04 (OTA-15)
Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
Nexus 5

#### Link to Debug Log
Please provide a link to debug. (Not sure how to do this)

Many thanks for any assistance!

**Comment by Flaburgan** [comment] 2021-01-26 22:05
Hello @ChrisAWC and thank you for taking time to report this bug! There is actually a problem in the way that Axolotl handles "received" status by Signal meaning that if your recipient is offline, the spinner will stay forever (see https://github.com/nanu-c/axolotl/issues/246#issuecomment-759090018). However, if you leave the chat (after a dozens of seconds, to be sure the picture is correctly sent) and go back to the chats list, and then open the chat again, the spinner shouldn't be there anymore.

There are other troubles currently with interactions with Signal so maybe your problem is a side effect. Can you please provide logs for us to know, they are at `.cache/upstart/click-application-textsecure-0.9.5.log` (or something similar, I'm saying this out of my mind).

**Comment by ChrisAWC** [comment] 2021-01-27 01:20
Hi Fla,
Many thanks for your reply.
The attached log file is from .cache/upstart/ . Is it the appropriate 
one? and should I upload it to Guthub?
Regards

**Comment by ChrisAWC** [comment] 2021-01-27 01:29
OK! I think that I might have answered my own question about uploading the log file.
Here it is
Regards
[application-click-textsecure.nanuc_textsecure_0.9.5.log.1.gz](https://github.com/nanu-c/axolotl/files/5877103/application-click-textsecure.nanuc_textsecure_0.9.5.log.1.gz)

**Comment by Flaburgan** [comment] 2021-02-15 09:29
@ChrisAWC can you confirm on which OS you are running Axolotl? Can you try to update it and tell us if the problem is still there?
@nanu-c if you want to have a look at the logs above if you find something interesting.

**Comment by nanu-c** [comment] 2021-02-18 12:51
I can reproduce it. Actually the attachment is sent successfully but not shown in the chat.

**Comment by nuehm-arno** [comment] 2021-09-27 20:15
Is this issue still present in v1.0.5? If not, please close the issue.

**Comment by nanu-c** [comment] 2022-01-07 17:18
Please try again and if it still happens we can reopen the issue.

**Closed by nanu-c** 2022-01-07 17:18 UTC
Labels: bug, to be confirmed
