### ISSUE TITLE
[BUG] Cannot register phone number

### ISSUE THREAD

**Issue by TriVoxel** [nanu-c/axolotl#964] opened 2022-12-13 15:16 UTC
### Description

I cannot register a phone number as it does not send a confirmation text after completing the Captcha.

#### Versions

1.6.0

#### Device

Google Pixel 3a (sargo)
Ubuntu Touch OTA 24 (xenial)

#### Link to Debug Log

[application-click-textsecure.nanuc_textsecure_1.6.0.log](https://github.com/nanu-c/axolotl/files/10219347/application-click-textsecure.nanuc_textsecure_1.6.0.log)

**Comment by josch** [comment] 2022-12-15 12:17
Sounds like a duplicate of #943

**Closed** 2022-12-27 15:39 UTC
