### ISSUE TITLE
Audio Messages

### ISSUE THREAD

**Issue by AA303** [nanu-c/axolotl#170] opened 2020-09-07 00:05 UTC
Would be great to have function to send an Audio Message

**Comment by flaun** [comment] 2020-09-27 16:58
is there anyone working on this right now? would be a great feature!:)

**Comment by Flaburgan** [comment] 2020-09-27 19:58
I'm closing this as a duplicate of https://github.com/nanu-c/axolotl/issues/108, no need to have two issues.

**Closed by Flaburgan** 2020-09-27 19:58 UTC
