### ISSUE TITLE
[BUG] Wrong link to qmlscene using "axolotl -e me"

### ISSUE THREAD

**Issue by nuehm-arno** [nanu-c/axolotl#291] opened 2020-12-16 19:32 UTC
### Description

Hello there,
following the descriptions from the Mobian Wiki to build Axolotl and starting the desktop file (axolotl -e me) with gtk-launch in a terminal, I stumbled over the following error message:

"FATA[0000] cmd.Start() failed with 'fork/exec /home/nanu/Qt/5.13.0/gcc_64/bin/qmlscene: no such file or directory''"

### Code

I found one code reference in the file app/ui/gui.go in line 111. But there may be more.

**Expected behavior:** link to "qmlscene"

#### Versions

0.9.0.1

#### Device
Mobian on PinePhone CE 3gb

**Comment by olof-nord** [comment] 2020-12-18 17:25
I suspect you mean the page here? https://wiki.mobian-project.org/doku.php?id=axolotl

Giving it a quick look, some steps seems to be a bit outdated.

Have you had a look at the documentation in this repository instead?
https://github.com/nanu-c/axolotl/blob/main/docs/INSTALL.md

We have snap, flatpak and appimage installs documented with a step-by-step guide for each install method.

**Comment by joshbowyer** [comment] 2020-12-18 22:51
Hey, author of that wiki page here. That page has seen a lot of activity over the past few days; I made an edit yesterday, but so far it should be correct, and you should not be using the `me` flag. Launch it with `qt` for standalone, or see the "daemonized server" method for the two-part method.

**Comment by nanu-c** [comment] 2020-12-18 22:52
Indeed this is wrong. We should either drop it or make it work
https://github.com/nanu-c/axolotl/blob/main/app/ui/gui.go#L111
```
} else if config.Gui == "me" {
		cmd = exec.Command("/home/nanu/Qt/5.13.0/gcc_64/bin/qmlscene", "--scaling", "guis/qml/Main.qml")
```

**Comment by joshbowyer** [comment] 2020-12-18 22:55
Is there any real difference between `me` and `qt` ? Or is it redundant now?

**Comment by nanu-c** [comment] 2020-12-18 23:03
I think it's redundant now, because this switch was only working on my Computer

**Comment by nuehm-arno** [comment] 2020-12-21 13:39
Thank you all for the answers. Maybe the redundancy should be mentioned somewhere.

And since we are in this topic: Which .qml file should be used by qmlscene / -e qt? Is it

`[...]/guis/qml/qml/MainQML.qml`
or
`[...]/guis/qml/Main.qml`

Having Axolotl as deamon (-e server) and starting qmlscene via terminal with one of the .qml files should start the UI, right?

MainQML.qml (which I think is used with "-e qt") is resulting in a white screen and some error messages:

`file://[...]/MainQML.qml:20: TypeError: Cannot read property 'left' of null`
Continuing with line 21 to 23 (top, right, bottom)
In addition, Axolotl is not starting the UI with "axolotl -e qt". There is only the white screen, too.

Main.qml is starting the UI correctly, only showing some errors like

`[[...]ERROR:gles2_cmd_decoder.cc(2843)] [GroupMarkerNotSet(crbug.com/242999)! [...]]`

Or am I just fiddling around to much?

I'd like to get Axolotl running smoothly without the need of a flatpak build.

**Comment by Flaburgan** [comment] 2021-01-26 22:25
@olof-nord maybe you could have a look at this?

**Comment by olof-nord** [comment] 2021-01-26 22:57
I have read along, but I must say that I am also a bit confused what the purpose, and difference, is between the three different QML files.

- guis/qml/qml/MainQML.qml
- guis/qml/ut/MainUt.qml
- guis/qml/Main.qml

I understand that the thee possible options to not use Axolotl with Electron are `ut`, `lorca` and `qt`.
All other -e values starts with electron. 

@nuehm-arno, I am not sure I understand what you want to achieve, or what the problem is.
Could you describe it with other words?

**Comment by nuehm-arno** [comment] 2021-01-27 11:50
I'm opening a new issue for the qml errors with -e qt for better understanding.

**Comment by nanu-c** [comment] 2021-02-11 10:27
axolotl -e me was removed, so i close this

**Closed by nanu-c** 2021-02-11 10:27 UTC
