### ISSUE TITLE
notification issuue

### ISSUE THREAD

**Issue by iam01110011** [nanu-c/axolotl#146] opened 2020-07-01 19:15 UTC
### Description

notification lights/ message sign only appear once I've opened the app. I wont get a notification of new message unless I open the app, then they appear 

### Steps to Reproduce

**Expected behavior:**the notification to appear even if I'm off the app

**Actual behavior:** notifications only appears once I've opened the app

**Reproduces how often:** all the time

#### Device
oneplus one

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`. I domt have this

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue. none?

thaaanks : )

**Comment by Flaburgan** [comment] 2020-07-01 19:20
This is a duplicate of https://github.com/nanu-c/axolotl/issues/14

**Comment by iam01110011** [comment] 2020-07-01 19:27
goddit!
thanks for the info buddy! just taking a look at #14s thread now : )

**Comment by nanu-c** [comment] 2020-08-14 20:23
It's a duplicate of #14  :)

**Closed by nanu-c** 2020-08-14 20:23 UTC
