### ISSUE TITLE
[feature request] add the ability to quote messages like official signal app does

### ISSUE THREAD

**Issue by sc0w** [nanu-c/axolotl#434] opened 2021-03-18 11:17 UTC
it would be nice if we have the ability to quote messages like official signal app does to improve communications.

**Comment by Flaburgan** [comment] 2021-03-18 12:44
Thank you for taking time to report an issue.
This is a duplicate of https://github.com/nanu-c/axolotl/issues/113

**Closed by Flaburgan** 2021-03-18 12:44 UTC
