### ISSUE TITLE
[BUG] unable to send messages

### ISSUE THREAD

**Issue by sc0w** [nanu-c/axolotl#551] opened 2021-08-28 16:36 UTC
### Description

I can receive messages, but I can't send messages

### Steps to Reproduce

1. Send message to one contact
2. I see the red triangle and the contact never receives it
3. I tried resetting the encryption but the same behavior, unable to send messages

**Expected behavior:**

It must can send messages properly

**Actual behavior:**

Unable to send messages

#### Versions

1.0.0 and 1.0.2

#### Device
mobian pinephone, probably this happens since the latest upgrade of packages (bookworm)

**Comment by sc0w** [comment] 2021-08-29 15:35
running in terminal I see:

```
time="2021/08/29 17:28:12" level=info msg="[axolotl-electron] Electron App load"
time="2021/08/29 17:28:14" level=info msg="[axolotl] Open chat with id:  1"
time="2021/08/29 17:28:14" level=debug msg="[axolotl] Enter chat  1"
time="2021/08/29 17:28:14" level=debug msg="[axolotl] sendMessageList for conversation 1"
time="2021/08/29 17:28:24" level=debug msg="[axolotl] send message to  1"
time="2021/08/29 17:28:24" level=debug msg="[textsecure] PUT /v1/messages/f10dfee3-bc74-4bb3-acfa-b20c4b48083e 401\n"
time="2021/08/29 17:28:24" level=error msg="[axolotl] send message error status code 401\n 0"
time="2021/08/29 17:28:24" level=info msg="[axolotl] status code 401\n"
time="2021/08/29 17:28:28" level=debug msg="[textsecure] PUT /v1/messages/f10dfee3-bc74-4bb3-acfa-b20c4b48083e 401\n"
time="2021/08/29 17:28:28" level=error msg="[axolotl] send message error status code 401\n 0"
time="2021/08/29 17:28:28" level=info msg="[axolotl] status code 401\n"
time="2021/08/29 17:28:31" level=debug msg="[axolotl] SendMessage f10dfee3-bc74-4bb3-acfa-b20c4b48083e 0"
time="2021/08/29 17:28:31" level=error msg="[axolotl] sending message failed  1630250911045"
time="2021/08/29 17:28:31" level=debug msg="[axolotl-ws] UpdateMessageHandlerWithSource  1 1630250911045"
time="2021-08-29T17:28:47+02:00" level=info msg="astikit: stopping worker..."
time="2021/08/29 17:28:47" level=debug msg="[axolotl-electron] open dev tools false"
time="2021-08-29T17:28:47+02:00" level=info msg="astikit: worker is now waiting..."
time="2021/08/29 17:28:47" level=error msg="[axolotl-ws] wsReader  websocket: close 1001 (going away)"
time="2021-08-29T17:28:47+02:00" level=error msg="'/home/mobian/.config/textsecure.nanuc/electron/vendor/electron-linux-arm64/electron' exited with code: -1"
time="2021-08-29T17:28:47+02:00" level=error msg="accept tcp 127.0.0.1:40063: use of closed network connection while TCP accepting"
```

**Comment by nuehm-arno** [comment] 2021-08-29 16:48
I found these possibly related changes in Signal Server made some days ago

https://github.com/signalapp/Signal-Server/commit/aeb9f67266be0c480ab7494968114e4791254f9b
https://github.com/signalapp/Signal-Server/commit/54fe3b9a436025240197e4eb7a0a354bfdc17c10
https://github.com/signalapp/Signal-Server/commit/a7443a9ece44d153e9372f03f1629abb157b996b

Maybe that helps for debugging...

**Comment by ateliernz** [comment] 2021-08-29 17:30
I have same behaviour on fp2

**Comment by Blackoverflow** [comment] 2021-08-29 22:26
> [signalapp/Signal-Server@aeb9f67](https://github.com/signalapp/Signal-Server/commit/aeb9f67266be0c480ab7494968114e4791254f9b)

No functional change

> [signalapp/Signal-Server@54fe3b9](https://github.com/signalapp/Signal-Server/commit/54fe3b9a436025240197e4eb7a0a354bfdc17c10)

new field `optional bool ephemeral`

> [signalapp/Signal-Server@a7443a9](https://github.com/signalapp/Signal-Server/commit/a7443a9ece44d153e9372f03f1629abb157b996b)
- MessageCache.java Line 152ff: Set Random Server GUID in message, if non is present.
- MessageManager.java Line 118: Only persist non ephemeral messages.
- WebSocketConnection.java Line 161: Clear ephemeral flag before sending the message

The rest are formatting changes or changes on what events they monitor.
I don't think a new optional field in TextSecure.proto is a reason for an error 401.
Thank you @nuehm-arno for looking for changes that may cause the problem though.

**Comment by Blackoverflow** [comment] 2021-08-30 00:18
I looked into reasons why the API "sendMessage" should return http 401 (unauthorized).

It does in this line:
https://github.com/signalapp/Signal-Server/blob/aeb9f67266be0c480ab7494968114e4791254f9b/service/src/main/java/org/whispersystems/textsecuregcm/controllers/MessageController.java#L212

The accessKey parameter hasn't changed since 2018 but there was a recent change on the "source".
I looked when the source would be empty and found this class:
https://github.com/signalapp/Signal-Server/blob/aeb9f67266be0c480ab7494968114e4791254f9b/service/src/main/java/org/whispersystems/textsecuregcm/auth/BaseAccountAuthenticator.java

Each instance of `return Optional.empty();` is a reason for a 401 error code.

I haven't yet found a plausible cause of our problem, though.

**Comment by nuehm-arno** [comment] 2021-08-30 08:52
Thanks @Blackoverflow for looking into this... Hopefully, we are not kicked out of the Signal servers eco-system.

**Comment by magdesign** [comment] 2021-08-30 20:09
> I have same behaviour on fp2

same on UBports

_off topic:
Its weird anyway that Brian Acton does not care in any way about niche phoneOS's, I mean Telegram may be unsecure and from a 
secret service, but this messenger runs even on a toaster or washing machine... time to move the closest friends to matrix_

**Comment by Cargocat440** [comment] 2021-09-02 08:44
Same on volla phone (UT OTA 18). Receiving messages but not able to send messages since 5 days.

**Comment by nanu-c** [comment] 2021-09-02 09:12
It's like that now, when you register you get an id + PW  to make API calls. But now you can only use this for downloading a certificate. 

With that certificate, your private and some crypto magic you can create new credentials to access the API. That means, you use your credentials including your uuid only once for login. 
That way, signal can ensure, they don't know who is knocking on their doors.
Axolotl hasn't implemented that yet, we only used always the credentials from the registration. And that was turned off now.

**Comment by ateliernz** [comment] 2021-09-12 19:09
It works now for me with 1.0.4 on UT

**Comment by c4pp4** [comment] 2021-09-13 00:00
After update to 1.0.4 there is a warning when starting: 

"Axolotl encountered an error communicating with Signal servers... If you think that something is wrong on your side, you can unregister and register again. Be careful, your encryption key will change and you will lose all your messages if you choose to do that."

What to do not to lose all messages?

**Comment by SolAZDev** [comment] 2021-09-13 02:45
This is still occouring for me, on UT, version 1.0.4

**Comment by nanu-c** [comment] 2021-09-13 20:59
Can you look in your config and see, if you still have `tel` und `uuid` set?

**Comment by c4pp4** [comment] 2021-09-14 08:41
> Can you look in your config and see, if you still have `tel` und `uuid` set?

In my case I have tel and uuid in config.yml

**Comment by 4c2** [comment] 2021-09-14 21:01
Even with unregister and trying to fresh register, I still get the same error "Axolotl encountered an error communicating with Signal servers..."

Version 1.0.4 used.

**Comment by nanu-c** [comment] 2021-09-14 21:50
Registering is currently broken, don't do that...
When that is merged, registering should work again https://github.com/nanu-c/axolotl/pull/560

**Comment by nuehm-arno** [comment] 2021-09-27 20:08
Should be resolved with v1.0.5... Please confirm and close the issue.

**Comment by mdehollander** [comment] 2021-09-28 07:23
For me the update fixed things!

**Comment by torfmaster** [comment] 2021-09-28 08:14
For me as well. Thanks a lot!

**Comment by Flaburgan** [comment] 2021-09-28 08:18
Nice to see 1.0.5 correctly solved that. I'm closing this issue.
In the same time, if you experience this regression: https://github.com/nanu-c/axolotl/issues/569 please comment there and provide logs.

**Closed by Flaburgan** 2021-09-28 08:18 UTC
Labels: bug, enhancement
