### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by joshbowyer** [nanu-c/axolotl#288] opened 2020-12-16 14:25 UTC
I'm sure this is already on the roadmap but here it is for itemization

**Comment by olof-nord** [comment] 2020-12-18 17:18
I have been looking into this for a while.

To be published, all dependencies of the application needs to be listed in the flatpak manifest.

This is completely doable for the go backend with the [go-get](https://github.com/flatpak/flatpak-builder-tools/tree/master/go-get) flatpak builder tool. The outcome is a list of 20-something dependencies, which are all listed with their fix versions under `sources`.

The big issue is for the axolotl-web dependencies.

Also for this there is a tool available, [flatpak-node-generator](https://github.com/flatpak/flatpak-builder-tools/blob/master/node/README.md). I have however never been able to successfully use it to parse the dependencies, and the dependencies of the dependencies and output it to a list.

I suspect this is due to the complexity of the relations between the dependencies in node_modules, as I have waited for several hours without any noticeable change.

Looking at other node-based flathub apps I have noticed that another solution is to just create a big archive of the dependencies, and add it as a single entry for the flatpak manifest `source`. This would then mean we have to host this file, and make sure to not delete it.

```
- name: axolotl-web
    sources:
      - type: archive
        url: "https://github.com/nanu-c/axolotl/tree/main/here-goes-the-file.tar.gz"
```

**Comment by joshbowyer** [comment] 2020-12-22 17:03
Would accidental deletion of a resource file in this git be an issue? haha

**Comment by joshbowyer** [comment] 2021-01-14 14:21
Is there a way to list the dependencies that were resolved and installed with flatpak-builder? If so then this should give a list which can be hosted as that tar.gz and used

**Comment by nanu-c** [comment] 2021-01-14 19:53
There are two lists https://github.com/nanu-c/axolotl/blob/main/go.sum and https://github.com/nanu-c/axolotl/blob/main/axolotl-web/package-lock.json
The ci can be tweaked to package the 2 files, but you need to ask @olof-nord for this.

**Comment by olof-nord** [comment] 2021-03-04 22:18
> Would accidental deletion of a resource file in this git be an issue? haha

You are of course right. I added an archive of the v0.9.9 node_modules for axolotl-web to the repo.

With it we can then, completely reproducible, list out all our dependencies (within the Flatpak Manifest and through an archive) and thus publish to Flathub.

**Comment by olof-nord** [comment] 2021-03-11 20:45
I am happy to say, we are all set for a Flathub publishing. MR is in place and once reviewed, we should be good to go. Currently the "web" version is published, later the "qt" version could be added as well.

> Build [41495 successful](https://flathub.org/builds/#/builders/32/builds/41495)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/39931/org.nanuc.Axolotl.flatpakref
> ```

**Comment by olof-nord** [comment] 2021-03-21 18:39
Axolotl is now published. Closing this issue!

https://flathub.org/apps/details/org.nanuc.Axolotl

**Closed by olof-nord** 2021-03-21 18:39 UTC

**Comment by joshbowyer** [comment] 2021-03-21 18:40
Is it published for QT? Because that's the main one we'd need IMO
