### ISSUE TITLE
[BUG] Unable to link devices

### ISSUE THREAD

**Issue by torfmaster** [nanu-c/axolotl#565] opened 2021-09-15 13:39 UTC
### Description

Curremtly, my instance of axolotl is unable to link devices (in this case signal desktop for mac).

### Steps to Reproduce

1. Scan qr code
2. click on "+" to add device
3. copy url tsdevice:/?uuid=<uuid>&pub_key=<pub_key> into text field of axolotl
4. confirm

**Expected behavior:** device is connected and appears under "connected devices"

**Actual behavior:** Nothing happens.

#### Versions

1.0.2.beta

#### Device
What device or OS are you using? pine64 logs

#### Link to Debug Log
Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
This file does not exist on my machine however, here is an excerpt from the logs:

```
INFO[2021/09/15 15:33:43] [axolotl] add device tsdevice:/?uuid=XXXX&pub_key=XXXXXX
found tsdeviceINFO[2021/09/15 15:33:43] AddNewLinkedDevice                           
DEBU[2021/09/15 15:33:44] [textsecure] GET /v1/devices/provisioning/code 401 
DEBU[2021/09/15 15:33:44] [textsecure] PUT /v1/provisioning/XXXXX 401 
ERRO[2021/09/15 15:33:44] status code 401                              
DEBU[2021/09/15 15:33:48] [textsecure] GET /v1/devices/ 401  
```

**Comment by ragreenburg** [comment] 2021-09-23 15:42
Duplicate of https://github.com/nanu-c/axolotl/issues/445 so probably close this issue and comment on there that this is still an issue.

**Comment by Flaburgan** [comment] 2021-09-23 15:44
Agree, closing in favor of #445.

**Closed by Flaburgan** 2021-09-23 15:44 UTC
