### ISSUE TITLE
[BUG] Cannot register device on ubuntu 20.04

### ISSUE THREAD

**Issue by pparent76** [nanu-c/axolotl#1015] opened 2023-03-22 12:49 UTC
Hi,

I've just done a fresh install of Ubports 20.04rc on my vollaphone.
I've installed axolotl, when going through the registration phase, I do not reveice the code by SMS. If I enter a random code in the interface I get "cannot communicate with Signal server" error.

(Note that I had a previous install of axolotl, on my previous ubports install, at first it worked fine and eventually the reception of messages started to be very random.)

EDIT: from the comments I see, I guess it's a known bug.

Thanks a lot for your work,
Best of luck.

**Comment by jakub-bidzan** [comment] 2023-03-23 21:50
Same happens on ubuntu touch 20.04 on google pixel 3A.

**Comment by nanu-c** [comment] 2023-03-24 06:29
duplicate of https://github.com/nanu-c/axolotl/issues/943

**Closed by nanu-c** 2023-03-24 06:29 UTC
