### ISSUE TITLE
No registration code

### ISSUE THREAD

**Issue by HSNijmegen** [nanu-c/axolotl#977] opened 2023-01-02 22:53 UTC
**On OnePlus One, Ubuntu Touch, stable Ubuntu 16.04 (OTA-24)**

**Steps to Reproduce**

> 1.Fresh installation of Ubuntu Touch (on OnePlusOne)
> 2.Install Axolotl
> 3.Install UT tweaks (and set prevent app suspension of Axolotl)
> 4.Edit "config.yml" to contain one line: "loglevel: debug" (place it in .config/textsecure.nanuc/)
> 5.Launch Axolotl
> 6.press "next" button
> 7.fill out telephone number (+countrycode + number)
> 8.press "request code" button
> 9.cross field "I am not a robot"
> 10.Solve 1 or more Capcha 
> 11.wait for the registration code (which does not arrive)

**Expected behavior**: one should get the code per sms

**Actual behavior:** no code arrives

**Versions**: 1.6.0 (installed from Ubuntu Touch OpenStore)

**Device:** OnePlusOne 

**Link to Debug Log**

Please provide a link to debug from ~/.cache/upstart/application-click-textsecure.nanuc_textsecure*.log
[application-click-textsecure.nanuc_textsecure_1.6.0.log](https://github.com/nanu-c/axolotl/files/10333661/application-click-textsecure.nanuc_textsecure_1.6.0.log)

**To be noticed:**

- The config.yml file in .config/textsecure.nanuc/config.yml is empty after launching Axolotl the first time (and ever after launching it again)
- The log file mentions multiple times that some AppArmor policies prevent some actions (is this the problem?)
- The log file also mentions "library "/vendor/lib/egl/libGLESv2S3D_adreno.so" can not be found. There is another library file called:  "/vendor/lib/egl/libGLESv2_adreno.so" could that be used instead?
- The log file also mentions: "file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches "
- Also tried a fresh sim-card (never used with Signal).

**Comment by nanu-c** [comment] 2023-02-13 23:50
duplicate of #943

**Closed by nanu-c** 2023-02-13 23:50 UTC
