### ISSUE TITLE
[BUG] Files accessible through axolotl

### ISSUE THREAD

**Issue by bjoern-tantau** [nanu-c/axolotl#140] opened 2020-05-13 12:57 UTC
### Description

Through /attachments I have access to every file axolotl has access to. This is especially problematic when the webserver isn't restricted to localhost because then everyone in the network can access the files.

### Steps to Reproduce

Open
http://localhost:9080/attachments?file=/etc/passwd in a browser

**Expected behavior:**

Browser gets a 403 for every file outside of the attachments folder.

**Actual behavior:**

I get the contents of /etc/passwd

#### Versions

0.8.2

**Comment by nanu-c** [comment] 2020-05-13 19:14
I will fix it asap, thanks for reporting

**Comment by Blackoverflow** [comment] 2020-06-09 14:23
@nanu-c my idea of fixing this would be to use the filename instead the full path as parameter. Should I give it a shot?

**Comment by nanu-c** [comment] 2020-06-09 16:58
For sure, if you want to try it. But the problem is, that the attachment has the fullpath and asks for it.

**Comment by nanu-c** [comment] 2020-08-14 20:37
Actually this bug is not so important in confined envirments. Nevertheless it's fixed now

**Closed** 2020-08-14 20:37 UTC
Labels: high-priority
