### ISSUE TITLE
[BUG] Unable to link to Signal desktop

### ISSUE THREAD

**Issue by Rargente** [nanu-c/axolotl#445] opened 2021-03-26 21:25 UTC
### Description

I am unable to link signal desktop with axolotl

### Steps to Reproduce

1. Open signal desktop
2. Scan QR code
3. Paste link into axolotl
4. Click "Finish Linking Device"

**Expected behavior:** [What you expect to happen]
Signal desktop links to axolotl

**Actual behavior:** [What actually happens]
Linking fails with error in Signal console:
Uncaught (in promise) Error: AccountManager.registerSecondDevice: Provision message was missing key data
    at /opt/Signal/resources/app.asar/ts/textsecure/AccountManager.js:162
(anonymous) @ /opt/Signal/resources/app.asar/ts/textsecure/AccountManager.js:162

#### Versions
Beta 0.9.9

#### Device
Axolotl on UBuntu Touch
Signal desktop on Windows 10 or Parrot Linux

### Excerpt from log file
[37mDEBU[0m[2021/03/26 18:23:49] [textsecure] Websocket sending message       
[36mINFO[0m[2021/03/26 18:23:53] [axolotl] add device tsdevice:/?uuid=###removed###&pub_key=###removed### 
found tsdevice[36mINFO[0m[2021/03/26 18:23:53] AddNewLinkedDevice                           
[37mDEBU[0m[2021/03/26 18:23:53] [textsecure] GET /v1/devices/provisioning/code 200 
[37mDEBU[0m[2021/03/26 18:23:53] [textsecure] PUT /v1/provisioning/###removed### 204 
[37mDEBU[0m[2021/03/26 18:23:53] [textsecure] GET /v1/devices/ 200            
[37mDEBU[0m[2021/03/26 18:24:01] [textsecure] Sending websocket ping message  
[37mDEBU[0m[2021/03/26 18:24:01] [textsecure] Received websocket pong message

**Comment by Danfro** [comment] 2021-09-12 18:32
@Rargente is this issue still valid? Linking to desktop should be fixed with the latest version from OpenStore.

Could you please confirm if the issue persists or also confirm&close if the issue is solved?

**Comment by nuehm-arno** [comment] 2021-09-27 20:10
Should be resolved with v1.0.5... Please confirm and close the issue.

**Comment by james-lyon** [comment] 2021-09-30 14:45
Is not resolved with v1.0.5 on my device (attempting to link Ubuntu Touch with Windows10 desktop).

Actual behavior: after pasting the QR code, there is no message and I am returned to the "No linked devices" screen.

**Comment by forfuks** [comment] 2021-10-06 14:38
not sure if this is relevent but when i look in the about section of the phone (redmi 7) and look in the storage all the installed apps have icons Axolotl has across in a circle

**Comment by DirkMetzler** [comment] 2021-12-06 23:27
After I have reset my signal account, I have now the same trouble connecting to signal-desktop as described by james-lyon: "after pasting the QR code, there is no message and I am returned to the "No linked devices" screen."

In the log file there is just an INFO message "add device tsdevice:...." but it is not working.

I am using Axolotl Beta 1.0.8 on the current Ubuntu touch version 18 on an FP2. The signal-desktop version is 5.17.2 on a SuseLinux Computer.

Many Thanks
Dirk

**Comment by nuehm-arno** [comment] 2021-12-07 07:53
@DirkMetzler Please update your Signal Desktop - there have been changes in the QR code.

**Closed** 2021-12-07 19:16 UTC
