### ISSUE TITLE
[BUG] Unable to import contacts

### ISSUE THREAD

**Issue by Jab2870** [nanu-c/axolotl#457] opened 2021-04-06 16:14 UTC
### Description

Contacts fail to import correctly

### Steps to Reproduce

Go to Contacts -> import contacts -> select vcard file

The following debug information is visible in the terminal:

```
│DEBU[2021/04/06 17:01:48] [axolotl] import vcf bytes written successfully 3131
│DEBU[2021/04/06 17:01:48] [axolotl] Import contact: Bob Bobbington
│ERRO[2021/04/06 17:01:48] [axolotl-ws] wsReader panic occurred: runtime error: index out of range [0] with length 0
│ERRO[2021/04/06 17:01:51] [axolotl-ws] send message writev tcp 127.0.0.1:9080->127.0.0.1:40904: use of closed network connection
│DEBU[2021/04/06 17:01:51] [axolotl-ws] remove client
│INFO[2021/04/06 17:01:51] [axolotl] Client Connected true
│DEBU[2021/04/06 17:01:51] [axolotl] send darkmode to client true
│DEBU[2021/04/06 17:01:51] [axolotl-ws] getRegistrationStatus
```

**Expected behavior:** 

The contacts should be imported

**Actual behavior:**

Nothing

#### Versions

Please provide the Version as written in `Settings->About Axolotl`

Beta 0.9.8

#### Device
What device or OS are you using?

Pinephone using running Arch Arm. Installed using Manjaro's pkgbuild:

https://github.com/manjaro-arm-community/axolotl

**Comment by Flaburgan** [comment] 2021-04-06 20:57
Duplicate of https://github.com/nanu-c/axolotl/issues/381

Also please upgrade, last version is 0.9.9.

**Closed by Flaburgan** 2021-04-06 20:57 UTC
