### ISSUE TITLE
Installation via clickable not successful

### ISSUE THREAD

**Issue by fabrei** [nanu-c/axolotl#74] opened 2019-09-03 20:04 UTC
### Description

In case of #73, I tried to install an older version of signal ut app. I followed the [installation introduction](https://github.com/nanu-c/textsecure-qml/#installation). I cloned this repository and changed to the commit bff3d5a for version 0.4.0. It worked until I have to run the command `clickable` in the main dir. I get the error 
```
adb: error: cannot stat '~/go/src/github.com/nanu-c/build/arm-linux-gnueabihf/app/textsecure.nanuc_0.4.0_all.click': No such file or directory
``` 
This is true, the dir `'~/go/src/github.com/nanu-c/build/arm-linux-gnueabihf/app/` exists, but the name of the click-file is `textsecure.nanuc_0.4.0_armhf.click` and not `textsecure.nanuc_0.4.0_all.click`. To fix it I changed the `architecture` in `textsecure-qml/click/manifest.json ` from `armhf` to `all`. That worked and the app was installed on my phone. Afterwards I called `clickable launch logs` and got the following error: 
```
** (process:5233): WARNING **: Unable to exec 'textsecure' in '/opt/click.ubuntu.com/.click/users/phablet/textsecure.nanuc': No such file or directory
```
I took a look into this dir and it looked like this:
```
ll /opt/click.ubuntu.com/.click/users/phablet/textsecure.nanuc/
total 72
drwxr-xr-x 3 clickpkg clickpkg  4096 Sep  3 21:40 ./
drwxr-xr-x 3 clickpkg clickpkg  4096 Sep  3 21:40 ../
drwxr-xr-x 5 clickpkg clickpkg  4096 Sep  3 21:40 .click/
-rwxr-xr-x 1 clickpkg clickpkg   419 Sep  2 22:01 notification.sh*
-rw-r--r-- 1 clickpkg clickpkg   258 Sep  3 17:24 textsecure.apparmor
-rw-r--r-- 1 clickpkg clickpkg   101 Sep  2 22:01 textsecure.content-hub
-rw-r--r-- 1 clickpkg clickpkg   194 Sep  2 22:01 textsecure.desktop
-rwxr-xr-x 1 clickpkg clickpkg    90 Sep  2 22:01 textsecure-helper*
-rw-r--r-- 1 clickpkg clickpkg  9849 Sep  3 17:24 textsecure.nanuc.pot
-rw-r--r-- 1 clickpkg clickpkg 14942 Sep  2 22:01 textsecure.png
-rw-r--r-- 1 clickpkg clickpkg   135 Sep  3 17:24 textsecure-push.apparmor
-rw-r--r-- 1 clickpkg clickpkg    36 Sep  2 22:01 textsecure-push-helper.json
-rw-r--r-- 1 clickpkg clickpkg    47 Sep  2 22:01 textsecure.url-dispatcher
```
There is no `textsecure` file or dir. If I install the current version 0.4.4 via openstore I get this dir overview:
```
phablet@ubuntu-phablet:~$ ll /opt/click.ubuntu.com/.click/users/phablet/textsecure.nanuc/
total 17724
drwxr-xr-x  7 clickpkg clickpkg     4096 Sep  3 21:51 ./
drwxr-xr-x  3 clickpkg clickpkg     4096 Sep  3 21:51 ../
drwxrwxr-x 11 clickpkg clickpkg     4096 Sep  3 21:51 app/
drwxr-xr-x  5 clickpkg clickpkg     4096 Sep  3 21:51 .click/
drwxrwxr-x  2 clickpkg clickpkg     4096 Sep  3 21:51 docs/
drwxrwxr-x  3 clickpkg clickpkg     4096 Sep  3 21:51 lib/
-rw-rw-r--  1 clickpkg clickpkg    32422 Jan 31  2019 LICENSE
-rwxrwxr-x  1 clickpkg clickpkg      419 Jan 31  2019 notification.sh*
drwxrwxr-x  3 clickpkg clickpkg     4096 Sep  3 21:51 qml/
-rw-r--r--  1 clickpkg clickpkg     3083 Aug 29 23:09 README.md
-rwxr-xr-x  1 clickpkg clickpkg 18032552 Aug 29 23:40 textsecure*
-rw-rw-r--  1 clickpkg clickpkg      258 Jan 31  2019 textsecure.apparmor
-rw-rw-r--  1 clickpkg clickpkg      101 Jan 31  2019 textsecure.content-hub
-rw-rw-r--  1 clickpkg clickpkg      194 Jan 31  2019 textsecure.desktop
-rwxrwxr-x  1 clickpkg clickpkg       90 Jan 31  2019 textsecure-helper*
-rw-rw-r--  1 clickpkg clickpkg    14942 Jan 31  2019 textsecure.png
-rw-rw-r--  1 clickpkg clickpkg      135 Jan 31  2019 textsecure-push.apparmor
-rw-rw-r--  1 clickpkg clickpkg       36 Jan 31  2019 textsecure-push-helper.json
-rw-rw-r--  1 clickpkg clickpkg       47 Jan 31  2019 textsecure.url-dispatcher
```
With this version I can start signal..

I already tried some other versions and everytime I got the same result. And instead of running `clickable` first, I called `clickable build` and after `clickable install build/arm-linux-gnueabihf/app/textsecure.nanuc_0.4.0_armhf.click`. The result was the same: no file or dir..

Any suggestions? Do I have to build textsecure separately? I expect, that clickable also installs textsecure automatically..

### Steps to Reproduce

1. see above..

**Expected behavior:** after installing signal ut app on the phone, it should start..

**Actual behavior:** it crashes with the error:
```
** (process:5233): WARNING **: Unable to exec 'textsecure' in '/opt/click.ubuntu.com/.click/users/phablet/textsecure.nanuc': No such file or directory
```

**Reproduces how often:** 100%

#### Versions
signal ut app 0.4.0/0.4.4/0.3.26

#### Device

oneplus one bacon ut 16.04 ota 10

**Comment by nanu-c** [comment] 2019-09-04 10:18
You need to use the `clickable.json` and the `scripts/postbuild.sh` from master  i think, because i had to adapt it changes of clickable

**Comment by fabrei** [comment] 2019-09-04 15:46
> You need to use the clickable.json

What do you mean? 

Now I first executed `scripts/postbuild.sh` and after it I followed the installation introductions. But I get the same error, that the dir/file is not existing.

**Comment by nanu-c** [comment] 2019-09-04 16:45
i mean you have to copy the two files to the old checkout, because without can not build it.
Or you use an old clickable version

**Comment by fabrei** [comment] 2019-09-04 17:44
For the 0.3.26 release I used clickable 3.2.0, like in your documentation. It uses an ubuntu 15.04 sdk. For the 0.4.0 release I used clickable 6.0.0 and this uses the 16.04 sdk. In 0.4.0 is already a `clickable.json` and `postbuild.sh`. For 0.4.0 I tried the versions of this two files from the current master branch. If I execute `clickable build` from `~/go/src/github.com/nanu-c`, it creates a `build` dir. After I execute `clickable install build/arm-linux-gnueabihf/app/textsecure.nanuc_0.4.0_armhf.click`. Whatever I try it is still the same result.

It is the first time I am using clickable; sorry if I am not using it the right way..

**Comment by nanu-c** [comment] 2019-09-04 20:31
okey, this is a problem in clickable, clickable 6 doesn't build go packages anymore

**Comment by nanu-c** [comment] 2019-09-04 20:39
https://gitlab.com/clickable/clickable/issues/144

**Comment by fabrei** [comment] 2019-09-04 22:12
it seems that clickable 4.0.0, 5.0.0 and 5.14.1 does not build go packages as well. I installed them and tried it with signal app version 0.4.0 and 0.3.27. I also tried it with the current `clickable.json` and `postbuild.sh` files in the master branch.

**Comment by nanu-c** [comment] 2019-09-05 09:44
fix-go has to be merged, https://gitlab.com/clickable/clickable/issues/146 has to be solved and this script has to be used https://github.com/nanu-c/textsecure-qml/blob/axolotl/scripts/postbuild.sh, but it's untested.
I will add that to master, too. The problem is clickable is not backwards compatible and also clickable uses one docker container for all versions and older versions of clickable are not compatible with the recent docker container

**Comment by nanu-c** [comment] 2019-09-05 10:00
build for `git checkout bff3d5affeb25c4d24f04fe0662f5b8d7a81d483`
Problem not compatible with clickable >v5.14.1
```
can't load package: package ..: no Go files in /home/nanu/go/src/github.com/nanu-c/textsecure-qml/build/arm-linux-gnueabihf
```
solution 
```
pip3 install git+https://gitlab.com/clickable/clickable.git@v5.14.1
```
Problem golang version in clickable changed, it's now case sensitive
```
/gopath/path0/src/github.com/nanu-c/textsecure/link.go:6:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```
solution:
* replace all Sirupsen  with sirupsen 

Then:
```
Successfully built package in './textsecure.nanuc_0.4.0_armhf.click'.
```

**Comment by fabrei** [comment] 2019-09-05 15:07
This does not work either. I checked out this commit, installed clickable v.5.14.1 and replaced sirupsen. 
In `~/go/src/github.com/nanu-c` I run `clickable` without any argument and get this output:

```
Auto detected template to be "pure"
Copied files to temp directory for click building
Using docker container "clickable/ubuntu-sdk:16.04-armhf"
Successfully built package in './textsecure.nanuc_0.4.0_armhf.click'.
adb: error: cannot stat '~/go/src/github.com/nanu-c/build/textsecure.nanuc_0.4.0_all.click': No such file or directory
Command 'b'adb push ~/go/src/github.com/nanu-c/build/textsecure.nanuc_0.4.0_all.click /home/phablet/'' returned non-zero exit status 1
```
The build process succeeds, but I don't understand, why clickable tries to push the `*_all.click` file instead of `*_armhf.click`. Anyway if I execute `clickable install build/textsecure.nanuc_0.4.0_armhf.click`, it is installed on the phone. But I get this output when I run `clickable launch logs:
```
** (process:28931): WARNING **: Unable to exec 'textsecure' in '/opt/click.ubuntu.com/.click/users/phablet/textsecure.nanuc': No such file or directory
```
So clickable does not build any go packages as you already mentioned.

Furthermore I used `clickable.json` as well as `postbuild.sh` of 0.4.0 commit. After I tried it with the new files from the current master branch with the 0.4.0 checkout. I also deleted the ubuntu sdk docker image and reinstalled it automatically with clickable.

If I use the master branch with clickable 5.14.1 or 6.0.2 it does not work as well. There are no go packages. But if I run `go build` in every dir `qml-go`, `textsecure`, `textsecure-qml` I do not get any error.

**Comment by nanu-c** [comment] 2019-09-05 18:30
`Auto detected template to be "pure"`
means clickable didn't found the clickable.json...

**Comment by nanu-c** [comment] 2019-09-05 18:44
[textsecure.nanuc_0.4.0_armhf.zip](https://github.com/nanu-c/textsecure-qml/files/3580761/textsecure.nanuc_0.4.0_armhf.zip)

**Comment by fabrei** [comment] 2019-09-05 21:40
Ok, I didn't get it, why the clickable.json is not found..And the message does not really make sense for me, because it does not tell that it could not be found..What should I do to build it right?
 
Thanks for the zip-file. I could install it, but if I send a message to a contact, the app crashes. But the message was successfully send. Here is the log: 
[application-click-textsecure.nanuc_textsecure_0.4.0.log](https://github.com/nanu-c/textsecure-qml/files/3581322/application-click-textsecure.nanuc_textsecure_0.4.0.log)

**Comment by fabrei** [comment] 2019-09-06 08:58
maybe you can upload version 0.3.261 until you fix #73 , because this was the last version which worked for me.

**Comment by nanu-c** [comment] 2019-09-14 21:22
Please try https://github.com/nanu-c/textsecure-qml/releases

**Comment by nanu-c** [comment] 2019-10-21 20:37
Now i merged the axolotl branch. It would be really helpfull if somebody could test if he/she can build it

**Comment by nanu-c** [comment] 2019-12-16 12:48
Please reopen when you try it again

**Closed by nanu-c** 2019-12-16 12:48 UTC
Labels: bug
