### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kmsgli** [nanu-c/axolotl#640] opened 2021-12-01 01:17 UTC
### Description

K button on keyboard not working

### Steps to Reproduce

1. [Install on Manjaro Phosh (pinephone)
2. [K button not working]

**Expected behavior:** [K button to work]

#### Versions

Beta 1.0.8

#### Device
PInephone Manjaro built from AUR package

**Comment by Ferenc-** [comment] 2021-12-01 13:22
Duplicate of #635

**Closed** 2021-12-06 17:22 UTC
